# Copyright (C) 2023 Wing Hei Chan

# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

source = "manuscript.tex"

max_repeat = 1
sequence = ["latex", "bibtex", "makeindex"]

[programs.bibtex]
command = "biber"
target = "reference.bib"
